// <auto-generated />
namespace KStypemig.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class FKDatPhong_DichVu_Nhanvien_khachHang : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FKDatPhong_DichVu_Nhanvien_khachHang));
        
        string IMigrationMetadata.Id
        {
            get { return "202405180930287_FKDatPhong_DichVu_Nhanvien_khachHang"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
