// <auto-generated />
namespace KStypemig.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class fk_review_khachhag : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fk_review_khachhag));
        
        string IMigrationMetadata.Id
        {
            get { return "202405181027063_fk_review_khachhag"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
