// <auto-generated />
namespace KStypemig.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class dc_fkdichvu_datph : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dc_fkdichvu_datph));
        
        string IMigrationMetadata.Id
        {
            get { return "202405230913486_dc_fkdichvu_datph"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
